BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[File] (
    [id] INT NOT NULL IDENTITY(1,1),
    [timestamp] DATETIME2 NOT NULL CONSTRAINT [File_timestamp_df] DEFAULT CURRENT_TIMESTAMP,
    [filename] NVARCHAR(1000),
    [link] NVARCHAR(1000),
    CONSTRAINT [File_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
